version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: Apogeu
    environment:
      POSTGRES_USER: ApogeuManager
      POSTGRES_PASSWORD: paraoalto
      POSTGRES_DB: apogeuDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
